### ISSUE TITLE
User Secrets For Updating Dynamic DNS Entries 

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-dyndns-host#1]
hey @ahdinosaur, hope this github issue finds you well (lol, but genuinely), 

glyph and I were just talking through some dynamic dns options, and @mycognosist mentioned that you might have had an idea for how to handle multiple users and multiple secrets, so that users can't update each other's dns entries. 

do you remember if you had something specific in mind?

**Comment by mhfowler** [comment]
so for now we are using TSIG keys on a per subdomain basis via nsupdate and bind9

**Comment by ahdinosaur** [comment]
hi @mhfowler, i'm not sure what ideas i had, what you're doing sounds great! :+1:
