### ISSUE TITLE
Rust Question: Snafu Variants

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-dyndns-host#5]
I've saved a branch to try to save a particular Rust bug I ran into. I think this might be a helpful pattern. Sometimes I encounter a compiler error that I don't fully understand, and then I can get around it, but actually I'd like to figure out what's going on. 

Here is the saved copy, and relevant lines:
https://github.com/peachcloud/peach-dyndns-host/blob/015a1914f74ca747b313522a0533f9003b95c5ae/src/http.rs#L46

This is the compiler error I get:
```
error[E0532]: expected unit struct, unit variant or constant, found struct variant `ServerError::TestError`
```

I'm having a bit of confusion understanding exactly what type Snafu Errors are, vs the enum variants of the error. It seems depending on how I reference the error, either just as TestError, or as ServerError::TestError , I get a different type of thing, and I would like to understand this better.

@mycognosist if you have time to take a look, or I could try the forum

**Comment by mycognosist** [comment]
@mhfowler 

Thanks for the ping. These sorts of investigations also contribute to my own learning journey :)

The compiler error index can be really useful in these cases, as it often includes failing and succeeding code examples. Here's the entry for the error you encountered: [E0532](https://doc.rust-lang.org/error-index.html#E0532) (you'll notice this at the beginning of the compiler error message).

> Pattern arm did not match expected kind.

You're trying to match on `ServerError::SecretMismatch` but your variant actually includes an anonymous struct as the value: `SecretMismatch { domain: String }`. To the compiler, those two type variants (one with `struct` and one without) are completely different. So you need to include the struct with `domain` in your match:

```rust
ServerError::SecretMismatch { domain } => Err(Status::Forbidden),
```

> It seems depending on how I reference the error, either just as TestError, or as ServerError::TestError

In the context of your code, `TestError` does not exist. It exists only as a variant of the `ServerError` enum, ie. `ServerError::TestError`. Trying to reference it as a standalone type will produce an error.

**Comment by mhfowler** [comment]
thanks, this is helpful! 

makes me wonder if someone has made a sort of Rust quiz and programming puzzles thing, 
almost like chess puzzles, 
where you could work through numerous examples 

feel like getting into the nitty gritty and weird edge cases like that might be helpful to my understanding, if such a thing exists

**Comment by mhfowler** [comment]
also ty for reference about error entries, hadn't seen that before

**Comment by mhfowler** [comment]
hmm interesting https://www.reddit.com/r/rust/comments/5fqpsm/rust_challenges/
https://exercism.io/
https://github.com/rust-lang/rustlings
