### ISSUE TITLE
Pair Programming: Sharing Resources Between http.rs and dns.rs

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-dyndns-host#6]
I was just trying to figure out how to share resources between the two servers, 
so that calls to the rocket endpoints, could actually effect what trust dns server was doing.

Of course one way to do this, would be to have trust DNS server read from sled as it starts, 
and whenever there are updates to the sled database, we restart the trust DNS server. 

But I'm guessing there is a way to dynamically do this without restarting the DNS server... but as I started to look into how to do this, I have a lot of questions. Perhaps a topic we could look at together in a pair programming session @mycognosist?

**Comment by mycognosist** [comment]
Yeah rad, this would be a fun thing to pair on. Have you noticed the [`watch_prefix`](https://docs.rs/sled/0.34.6/sled/struct.Tree.html#method.watch_prefix) method on `sled::Tree`?

That appears to offer a neat solution for your imagined flow:

> Of course one way to do this, would be to have trust DNS server read from sled as it starts,
and whenever there are updates to the sled database, we ~~restart the trust DNS server~~ receive the event and take appropriate action.

:)

**Comment by mhfowler** [comment]
hadn't seen watch_prefix, this looks like a great solution

for the sake of rust learning, I'm also somewhat curious how one would communicate between the processes without something already implemented to do this in sled (watch_prefix)

but watch_prefix is actually a great solution

**Comment by mycognosist** [comment]
We can definitely talk about IPC (Inter-Process Communication) options in more detail. One relatively straight-forward way to do that is using pipes. So you could have one process start the second one as a child - that gives you a handle to the `stdin` of the second process, allowing you to pass in data.

Another way is to use a named pipe and do FIFO (First In First Out). [Here's a code example which uses bincode to (de)serialize the messages](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3359f7575a71a077409ba0d6b16a6098) (authored by [alice](https://users.rust-lang.org/u/alice)).

**Comment by mhfowler** [comment]
@mycognosist this isn't want I was imagining, but this is  also very interesting -- I could have been more specific -- I originally was wondering if there was a possibility within rust (without the file system) about inter-thread communication. The current way it is written, the rocket server, and the DNS server, both get created as separate threads, that get started in main.rs. 

I was hoping the DNS code might be able to return some object which could then be utilized in the rocket thread, to talk to to the DNS thread. But when I started doing this, I ran into ownership problems (perhaps Rust protecting me from myself). 

For example in python, I might create an object dns_server, and pass dns_server as a variable when I instantiate rocket::serve, and then in the rocket handlers, when I receive info, I might call dns_server.update(domain, new_ip_address), and the dns_server object would have the things it needs to handle that. 

Not sure if that makes sense. I think my main question is how to share objects, or if trust_dns objects like Authority is intentionally preventing itself from being shared in that way.

**Comment by mycognosist** [comment]
Ah I see, I misunderstood. I didn't look at the code and assumed you were talking about processes and not threads.

If I understand correctly, what you're asking boils down to: "how do I communicate between threads?"

Message passing is a central concept of concurrency in Rust and is accomplished via channels (a near-identical concept to what I outlined above regarding pipes). I suggest taking a look at this page of the Rust Book: [Message Passing](https://doc.rust-lang.org/book/ch16-02-message-passing.html). Better yet, read that whole chapter (_Fearless Concurrency_). In my experience to date, passing messages is simpler than sharing state (ie. passing an object around). Understanding these high-level concepts will help you when it comes to implementation details.

When it comes to a channel crate, I recommend taking a look at [crossbeam-channel](https://docs.rs/crossbeam-channel/0.5.1/crossbeam_channel/).

I think I have some past-projects using channels. I'll have them handy for our session.

**Comment by mhfowler** [comment]
Ok this looks great. I'm looking forward to learn about this. 

I've also realized that the ownership issue I'm seeing, will still be an issue with any of these solutions haha, which is good news, because it means I get to try to learn about ownership too still...

Here is the line in my current code where I get the borrow issue https://github.com/peachcloud/peach-dyndns-host/blob/76dc8065838acfbe752d818d4555315a4b4d6429/src/dns.rs#L91

```
89 |     authority.upsert(dyn_record, authority.serial());
   |     ^^^^^^^^^ value borrowed here after move
```

... need to figure out how to call .upsert multiple times ,  when currently authority gets moved when authority.upsert gets called 

we can talk through it on Friday

**Comment by mycognosist** [comment]
I'm happy we made some progress on this :)

**Comment by mycognosist** [comment]
@mhfowler 

Do you mind if we close this issue?

**Comment by mhfowler** [comment]
@mycognosist it turns out it may be a little more complicated still then we got to via pair programming, but I'm still making progress / have some ideas, so I'll close this and may just re-open if I reach a future road block

**Comment by mycognosist** [comment]
@mhfowler 

OK sounds like a plan. Please reach out if I can help or if my code mutterings might be of service :)

**Comment by mhfowler** [comment]
in case I come back to this, saving that
- using the trust-dns-client to create records yields not yet implemented response code https://github.com/peachcloud/peach-dyndns-host/blob/5f2ea71f03612f1cb94092dfc7d64f668595dee5/src/client.rs#L62
- using nsupdate yields not yet implemented response code https://github.com/peachcloud/peach-dyndns-host/blob/create-record/bash/nsupdate.sh

**Comment by mhfowler** [comment]
I've also tried using watch_prefix ... but I'm having an issue with sled when I run two separate threads or processes that access the same sled database:
```
thread 'main' panicked at 'Failed to open sled db: Io(Custom { kind: Other, error: "could not acquire lock on \"./sled_data/db\": Os { code: 35, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })', src/db_test.rs:45:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I though sled was supposed to be able to do this, but so far I see this error whenever I try to open a sled_db in two separate threads

**Comment by mhfowler** [comment]
Possible paths forward:
- figure out sled concurrency issue 
- try using SqliteAuthority in trust-dns to see if it supports update requests as advertised
- switch to using Bind9 server instead of trust-dns

**Comment by mhfowler** [comment]
instead of using trust-dns internals directly through rust, 
I'm looking into just running it as a binary and sending update requests, 
via a configuration file like this https://github.com/bluejekyll/trust-dns/blob/main/tests/test-data/named_test_configs/example.toml
